services:
  db:
    image: postgres:16
    container_name: sports_articles_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sports_articles
      POSTGRES_USER: sports
      POSTGRES_PASSWORD: sports
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
